chat:
  port: ":10002"

map:
  port: ":10003"

service:
  port: ":10004"

jwt:
  defaultStrategy: "snowflake"
  secretKey: "8FFAA81BAAFDBAE5E02F71708D252B6D122544F469B2A6498023BFD2C01273A276286D7E8B2E34B4D13AFF85323966BBA6757C99ED9DA48FB66371370E8E14F6"
  expiresIn: 7d

db:
  host: localhost
  username: root
  password: Vika881843905#$
  dbname: snowflake
  maxOpenConns: 10
  SetMaxIdleConns: 5

s3:
  accessKeyId: "002a0da47845c670000000003"
  secretAccessKey: "K002Gga7fxkL6xNwvSNZbT+367HKlW0"
  region: "us-west-002"
  endpoint: "s3.us-west-002.backblazeb2.com"
  bucketName: "yukki-studio"
  keyNamePrefix: "snowflake/generated-ai-image/"

openai:
  secretKey: "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"

novelai:
  apiKey: "UCDcf6w9i_FVWKy5nRCk7gatoIfJaXX2LIrj2ScTZap8hFYFqko8ZqajwrRg5M4H"
